In [ ]:
(5,7)

In [ ]:
5, 7

In [ ]:
(5,)

In [1]:
list_a = [1, 3, 5, 7, 9]
list_b = [3, 5, 6, 7, 9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [2]:
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [3]:
import numpy as np
array_a = np.array([1,3,5,7,9])
array_b = np.array([3,5,6,7,9])
type(array_a)
array_a + array_b


array([ 4,  8, 11, 14, 18])

In [4]:
import numpy as np
l =[[1,2,3],[2,3,4]]
array=np.array(l)
array.ndim, array.shape,array.dtype

(2, (2, 3), dtype('int64'))

In [5]:
import numpy as np
np.random.randn(10,5)

array([[ 1.02007304, -0.32662488, -0.56321625, -0.44468994,  0.00472108],
       [ 0.56312315,  0.02906112, -2.57336845,  0.12082159,  0.2299861 ],
       [ 0.71273295, -1.93096013, -1.87567917,  1.8248099 , -0.70041856],
       [-0.29374605,  0.39492758,  2.02493034, -0.05968376,  0.0505973 ],
       [-1.31738855,  0.62473751,  0.82735022, -0.00409145, -0.51289955],
       [ 2.88275952,  0.13529259,  1.48488777,  0.05848389,  0.27937817],
       [-0.30004964,  0.08017751, -0.40294864, -0.5165886 ,  0.22952945],
       [-1.03645754, -1.17773745, -0.14772555, -0.35377884,  1.58403951],
       [ 0.36622325, -0.4473551 , -0.77542929,  0.2799739 ,  0.04122803],
       [ 0.73487431,  0.87404556, -0.59431121,  0.97827054, -0.10547006]])

In [6]:
#50個學生,每個學生有5個分數(50-100)
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 74,  91,  84,  62,  86],
       [ 68,  88,  89,  92,  84],
       [ 88,  80,  65,  71,  65],
       [ 77,  91,  67,  75,  74],
       [ 96,  70,  74,  99,  86],
       [ 95,  59,  66,  85,  94],
       [ 90,  53,  67,  60,  73],
       [ 57, 100,  53,  82,  84],
       [ 83,  64,  87,  52,  85],
       [ 66,  72,  71,  82,  90],
       [ 57,  62,  80,  89,  86],
       [ 95,  83,  83,  53,  74],
       [ 74,  71,  99,  57,  78],
       [ 89,  50,  85,  65,  67],
       [ 74,  94,  64,  84,  88],
       [ 75,  52,  82,  67,  98],
       [ 92,  71,  96,  63,  97],
       [100,  65,  53,  55,  61],
       [ 50,  72,  85,  67,  67],
       [ 72,  62,  64,  55,  90],
       [ 57,  73,  68, 100,  56],
       [ 72,  80,  94,  64,  50],
       [ 90,  70,  52,  89,  58],
       [ 96,  57,  61,  59,  91],
       [ 94,  56,  72,  86,  83],
       [ 98,  80,  78,  93,  81],
       [ 71,  63,  84,  80,  95],
       [ 79,  98,  64,  76,  93],
       [ 90,  85,  72,  72,  80],
       [ 61,  

In [8]:
#第一個學生
scores[0,:]
#前5個學生
scores[:5,:]
#最後5個學生
scores[-5:,:]

array([[ 93,  83,  95,  92,  88],
       [ 79,  98,  78,  98,  54],
       [ 91,  78,  68,  60,  86],
       [ 51,  94,  91,  64,  85],
       [100,  75,  84,  74,  91]])

In [9]:
#全班第1科的分數
scores[:,0]

array([ 74,  68,  88,  77,  96,  95,  90,  57,  83,  66,  57,  95,  74,
        89,  74,  75,  92, 100,  50,  72,  57,  72,  90,  96,  94,  98,
        71,  79,  90,  61,  64,  52,  80,  67,  62,  70,  53,  68,  52,
        64,  91,  91,  66,  65,  90,  93,  79,  91,  51, 100])

In [11]:
#全班第2科的分數
scores[:,1]

array([ 91,  88,  80,  91,  70,  59,  53, 100,  64,  72,  62,  83,  71,
        50,  94,  52,  71,  65,  72,  62,  73,  80,  70,  57,  56,  80,
        63,  98,  85,  60,  96,  94,  76,  95,  80,  64,  76,  70,  85,
        69,  88,  78,  69,  94,  61,  83,  98,  78,  94,  75])

In [12]:
#每位學生的總分
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4] 
total

array([397, 421, 369, 384, 425, 399, 343, 376, 371, 381, 374, 388, 379,
       356, 404, 374, 419, 334, 341, 343, 354, 360, 359, 364, 391, 430,
       393, 410, 399, 336, 357, 355, 409, 339, 344, 377, 363, 300, 401,
       371, 430, 394, 350, 393, 321, 451, 407, 383, 385, 424])

In [13]:
#使用統計的方法
#每個學生總分
np.sum(scores,axis=1)


array([397, 421, 369, 384, 425, 399, 343, 376, 371, 381, 374, 388, 379,
       356, 404, 374, 419, 334, 341, 343, 354, 360, 359, 364, 391, 430,
       393, 410, 399, 336, 357, 355, 409, 339, 344, 377, 363, 300, 401,
       371, 430, 394, 350, 393, 321, 451, 407, 383, 385, 424])

In [15]:
#每個學生平均
np.mean(scores,axis=1)

array([79.4, 84.2, 73.8, 76.8, 85. , 79.8, 68.6, 75.2, 74.2, 76.2, 74.8,
       77.6, 75.8, 71.2, 80.8, 74.8, 83.8, 66.8, 68.2, 68.6, 70.8, 72. ,
       71.8, 72.8, 78.2, 86. , 78.6, 82. , 79.8, 67.2, 71.4, 71. , 81.8,
       67.8, 68.8, 75.4, 72.6, 60. , 80.2, 74.2, 86. , 78.8, 70. , 78.6,
       64.2, 90.2, 81.4, 76.6, 77. , 84.8])